### ISSUE TITLE
Cannot use string manipulation methods on converted numbers to words.

### ISSUE THREAD

**Issue by malthew** [marlun78/number-to-words#38]
I cannot seem to manipulate a number that has been converted to a string, using string methods such as `.split()`, `.replace()` or `.join()`.
I'm using TypeScript and React.

Example:

```TypeScript
var numberToWords = require('number-to-words');
var id = 1526;
var idWord: string = numberToWords.toWords(id);
idWord.replace(' ', '');
console.log(idWord)    // Returns 'one thousand, five hundred twenty-six' instead of the correct 'onethousand,fivehundredtwenty-six'
```

**Comment by cloudorbush** [comment]
can confirm this also happens when capitalizing the result.

**Comment by Dinkelborg** [comment]
I'm having the exact same issue and its like almost a year later has anyone found any workaround? 
Its extremely random as the type of the return value is string what could even cause it to no longer be changeable?

**Comment by marlun78** [comment]
When using [`String.prototype.replace`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) with a string as input, only the first occurence is replaced. If you want to replace all spaces in a string, use the RegExp version with the global flag (`g`), like so `idWord.replace(/ /g, '')`, or use the new [String.prototype.replaceAll](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll) like so, `idWord.replaceAll(' ', '');`.

**Comment by Dinkelborg** [comment]
@marlun78 - sorry but thats definitely not the correct answer - and this is still an issue so please reopen it. 
I am using: 
`console.log(">>>>>>>", conf.formattedId);
    conf.formattedId.replace(/\s/g, "");
    console.log(">>>>>>>", conf.formattedId);`
    
   I also tried the replaceAll function and it doesn't work

**Comment by marlun78** [comment]
Sorry, but you need to provide more info than that. It must be enough for me to reliably reproduce the issue.



On 13 Sep 2022, at 14:31, Dinkelborg ***@***.***> wrote:

﻿

@marlun78<https://github.com/marlun78> - sorry but thats definitely not the correct answer - and this is still an issue so please reopen it.
I am using:
console.log(">>>>>>>", conf.formattedId); conf.formattedId.replace(/\s/g, ""); console.log(">>>>>>>", conf.formattedId);

I also tried the replaceAll function and it doesn't work
