### ISSUE TITLE
Unexpected ordinal numerals when traversing an array

### ISSUE THREAD

**Issue by tehawanka** [marlun78/number-to-words#45]
```
var numberToWords = require("number-to-words");
const tw = numberToWords.toWords;
[1,4,5,7].map((d) => tw(d));
[1,4,5,7].map(tw);
```

When the library is used with an implicit passed parameter (second example), every array element except the first is an ordinal numeral:
The result of `[1,4,5,7].map((d) => tw(d));` is ["one", "four", "five", "seven"]
The result of `[1,4,5,7].map(tw);` is: ["one", "fourth", "fifth", "seventh"]

**Comment by marlun78** [comment]
That's because `toWords` takes a second optional (and now deprecated) argument.
https://github.com/marlun78/number-to-words/blob/master/src/toWords.js#L33
With the current version you'll have to use the first of the two examples above.

**Comment by tehawanka** [comment]
Ok, thanks for clarifying!
