### ISSUE TITLE
I get isFinite Error

### ISSUE THREAD

**Issue by Kolajosh** [marlun78/number-to-words#46]
i get this error when trying to convert number to words

TypeError: Not a finite number: undefined (undefined)
    at Object.j [as toWords]

**Comment by marlun78** [comment]
Can you provide tests to prove the issue?

**Comment by Kolajosh** [comment]
Hi @marlun78 
So i realized that i wasn't passing a number.
I converted it to a number, and it works fine now
Thanks for your swift response
